name: CI/CD Pipeline
on:
  push:
    branches: [feature/ci-cd-and-deployment]
  pull_request:
    branches: [feature/ci-cd-and-deployment]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run lint
        run: npm run lint
      
      - name: Run unit tests
        run: npm run test
      
      - name: Run Cypress tests
        run: npm run cypress:run
      
      - name: Build production
        run: npm run build:prod
      
      - name: Verify build
        run: |
          ls -la build
          [ -f build/index.html ] || exit 1

  deploy:
    needs: test-and-build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      
      - name: Deploy to Vercel
        run: vercel --prod --confirm
       