name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }} 
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run code formatting
        run: yarn format
        
      - name: Run lint
        run: yarn lint
      
      - name: Run unit tests
        run: yarn test
      
      - name: Run Cypress tests
        run: |
          yarn start &
          yarn wait-on http://localhost:4000
          yarn cypress:run
      
      - name: Build production
        run: yarn build:prod

  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}  
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      
      - name: Deploy Preview
        run: |
          vercel --yes --token ${{ secrets.VERCEL_TOKEN }} \
            --name feature-${{ github.event.pull_request.number }} \
            --meta pullRequestId=${{ github.event.pull_request.number }}

  deploy-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest  
      
      - name: Deploy to Production
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
