name: CI/CD Pipeline

on:
  push:
    branches: ['**']  
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  test-and-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x  
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run code formatting
        run: yarn format
        
      - name: Run lint
        run: yarn lint
      
      - name: Run unit tests
        run: yarn test
      
      - name: Run Cypress tests
        run: |
          yarn start &
          yarn wait-on http://localhost:4000
          yarn cypress:run
      
      - name: Build production
        run: yarn build:prod

  deploy-on-merge:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x   
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest  
      
      - name: Deploy to Vercel
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}

  deploy-on-push:
    if: github.event_name == 'push'  
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x  
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest  
      
      - name: Deploy to Vercel
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
