name: CI/CD Pipeline
on:
  push:
    branches: [feature/ci-cd-and-deployment]
  pull_request:
    branches: [feature/ci-cd-and-deployment]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run lint
        run: yarn lint
      
      - name: Run unit tests
        run: yarn test
      
      - name: Run Cypress tests
        run: |
          yarn start &
          yarn wait-on http://localhost:4000
          yarn cypress:run
      
      - name: Build production
        run: yarn build:prod

  deploy:
    needs: test-and-build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest  
      
      - name: Deploy to Vercel
        run: vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
